name: auto-escape-invalid-characters-in-locales

on:
  pull_request:
  push:
    branches:
      - "trunk"

jobs:
  auto-escape-invalid-characters-in-locales:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: trunk
    - name: escape ZWSP unexpectedly unescaped by GitLocalize
      run: "ZWSP=$'\\u200b'; grep -r -E \"$ZWSP\" webextensions/_locales | cut -d : -f 1 | uniq | xargs sed -i -E -e \"s/$ZWSP/\\\\\\\\u200b/g\" || echo 'there is no fixable files'"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Escape invalid characters in locales
        file_pattern: webextensions/_locales/*/*.json
        branch: trunk
 